name: test_ktlint_format_and_test_code_CI

on:
  pull_request:
    branches:
      - '*'
      
jobs:
  ktlint:
    name: ktlint_and_test
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: ./gradlew dependencies
        
      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Tests 
        run: ./gradlew test
