name: test_ktlint_format_and_test_code_CI

on:
  pull_request:
    branches:
      - '*'
      
jobs:
  ktlint:
    name: ktlint_check
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Install dependencies
        run: ./gradlew dependencies
        
      - name: Run ktlint
        run: ./gradlew ktlintCheck
        
  test:
    name: test_code
    runs-on: ubuntu-latest  
    needs: ktlint  

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Install JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run Tests  # 단계 이름 수정
        run: ./gradlew test
